name: 'Trelnex.MonoTag'
description: 'Automatically bump semantic version tags with configurable prefixes for monorepo projects'
author: 'Steven Kehrli'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  tag_prefix:
    description: 'The prefix for the tag name (e.g., "trelnex-core-" will create tags like "trelnex-core-1.2.3").'
    required: true
    type: string
  tag_part:
    description: 'The part of the semantic version to bump. Must be one of: "major", "minor", or "patch".'
    required: true
    type: string
outputs:
  new_tag:
    description: 'The complete new tag that was created (including prefix)'
  new_semver:
    description: 'The semantic version portion of the new tag (without prefix)'
branding:
  icon: 'git-merge'
  color: 'purple'
